defmodule RustQ.Codegen do
  @moduledoc false

  alias RustQ.Codegen.DecoderHelpers
  alias RustQ.Codegen.Decoders
  alias RustQ.Codegen.Dispatch
  alias RustQ.Codegen.Helpers
  alias RustQ.Codegen.Modules
  alias RustQ.Rust
  alias RustQ.Rust.AST.Builder, as: A

  def generated_ast_support(opts \\ []) do
    [
      A.use({[:rustler], [:Atom, :Env, :NifResult, :Term]}),
      A.use(
        {[:syn],
         [
           :Arm,
           :Expr,
           :Field,
           :FnArg,
           :Item,
           :ItemConst,
           :ItemEnum,
           :ItemFn,
           :ItemImpl,
           :ItemMod,
           :ItemStruct,
           :ItemStatic,
           :ItemType,
           :ItemUse,
           :Pat,
           :Path,
           :Stmt,
           :Type,
           :Variant
         ]}
      ),
      Modules.asts(),
      Helpers.asts(),
      DecoderHelpers.asts(),
      Dispatch.asts(),
      Decoders.asts()
    ]
    |> List.flatten()
    |> Rust.render_all()
    |> RustQ.render!("generated_ast.rs", Keyword.put_new(opts, :rustfmt, true))
    |> then(&"// This file is generated by RustQ. Do not edit by hand.\n\n#{&1}")
  end
end
