// This file is generated by RustQ. Do not edit by hand.

mod atoms {
    rustler::atoms! {
        anchor, attrs, clear, content, element, end, is_static, keep_alive, kind, loc,
        prop_kind, regular, set_prop, start, text, r#type = "type", value, values
    }
}
pub(crate) fn encode_op<'a>(env: rustler::Env<'a>, value: &Op<'_>) -> rustler::Term<'a> {
    match value {
        Op::SetProp(field0) => {
            encode_set_prop(env, field0)
                .map_put(atoms::kind().encode(env), atoms::set_prop().encode(env))
                .unwrap()
        }
        Op::Text { element, values } => {
            rustler::Term::map_from_arrays(
                    env,
                    &[
                        atoms::kind().encode(env),
                        atoms::element().encode(env),
                        atoms::values().encode(env),
                    ],
                    &[
                        atoms::text().encode(env),
                        element.encode(env),
                        values
                            .iter()
                            .map(|item0| encode_expr(env, item0))
                            .collect::<Vec<rustler::Term<'a>>>()
                            .encode(env),
                    ],
                )
                .unwrap()
        }
        Op::Anchor(field0) => {
            rustler::Term::map_from_arrays(
                    env,
                    &[atoms::kind().encode(env), atoms::value().encode(env)],
                    &[atoms::anchor().encode(env), field0.encode(env)],
                )
                .unwrap()
        }
        Op::Clear => {
            rustler::Term::map_from_arrays(
                    env,
                    &[atoms::kind().encode(env)],
                    &[atoms::clear().encode(env)],
                )
                .unwrap()
        }
    }
}
pub(crate) fn encode_set_prop<'a>(
    env: rustler::Env<'a>,
    value: &SetProp<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[
                atoms::element().encode(env),
                atoms::values().encode(env),
                atoms::loc().encode(env),
                atoms::prop_kind().encode(env),
                atoms::r#type().encode(env),
                atoms::attrs().encode(env),
            ],
            &[
                value.element.encode(env),
                value
                    .values
                    .iter()
                    .map(|item0| encode_expr(env, item0))
                    .collect::<Vec<rustler::Term<'a>>>()
                    .encode(env),
                value
                    .loc
                    .as_ref()
                    .map(|item0| encode_loc(env, item0))
                    .unwrap_or_else(|| rustler::types::atom::nil().encode(env)),
                encode_kind(env, &value.kind),
                encode_name(env, &value.r#type),
                rustler::Term::map_from_pairs(
                        env,
                        &value
                            .attrs
                            .iter()
                            .map(|(key0, item0)| (
                                key0.as_str().encode(env),
                                encode_expr(env, item0),
                            ))
                            .collect::<Vec<(rustler::Term<'a>, rustler::Term<'a>)>>(),
                    )
                    .unwrap(),
            ],
        )
        .unwrap()
}
pub(crate) fn encode_expr<'a>(
    env: rustler::Env<'a>,
    value: &Expr<'_>,
) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::content().encode(env), atoms::is_static().encode(env)],
            &[value.content.encode(env), value.is_static.encode(env)],
        )
        .unwrap()
}
pub(crate) fn encode_loc<'a>(env: rustler::Env<'a>, value: &Loc) -> rustler::Term<'a> {
    rustler::Term::map_from_arrays(
            env,
            &[atoms::start().encode(env), atoms::end().encode(env)],
            &[value.start.encode(env), value.end.encode(env)],
        )
        .unwrap()
}
pub(crate) fn encode_kind<'a>(env: rustler::Env<'a>, value: &Kind) -> rustler::Term<'a> {
    match value {
        Kind::Regular => atoms::regular().encode(env),
        Kind::KeepAlive => atoms::keep_alive().encode(env),
    }
}
pub(crate) fn encode_name<'a>(env: rustler::Env<'a>, value: &Name) -> rustler::Term<'a> {
    value.0.as_str().encode(env)
}
