defmodule RustQ.Native.Build do
  @moduledoc false

  alias RustQ.Native.Manifest
  alias RustQ.Rust.AST.Builder, as: A
  alias RustQ.Rustler.Nif

  def maybe_build_and_loader(module, items, opts) do
    if opts[:build] do
      build_and_loader(module, items, opts)
    end
  end

  defp build_and_loader(module, items, opts) do
    crate = Keyword.fetch!(opts, :crate)
    otp_app = Keyword.fetch!(opts, :otp_app)
    mode = Keyword.fetch!(opts, :mode)
    cargo = Keyword.fetch!(opts, :cargo)
    root = Path.join([Mix.Project.build_path(), "rustq_native", crate])
    manifest = Path.join(root, "Cargo.toml")
    source_path = Path.join([root, "src", "lib.rs"])
    target = Path.join(root, "target")
    source = native_source(items, module)
    write_if_changed!(manifest, Manifest.encode!(crate, opts[:crates]))
    write_if_changed!(source_path, source)
    format_crate!(cargo, manifest, module)
    build_crate!(cargo, manifest, target, mode, module)

    if opts[:load] do
      destination = install_library!(target, mode, crate, otp_app)
      relative_library = Path.join("priv/native", Path.rootname(Path.basename(destination)))

      quote do
        @on_load :__rustq_load_nif__
        @doc false
        def __rustq_load_nif__ do
          :code.purge(__MODULE__)

          path =
            unquote(otp_app) |> Application.app_dir(unquote(relative_library)) |> to_charlist()

          :erlang.load_nif(path, 0)
        end
      end
    end
  end

  def prepare_manifest!(opts) do
    root = Path.join([Mix.Project.build_path(), "rustq_native", opts[:crate]])
    manifest = Path.join(root, "Cargo.toml")
    source = Path.join([root, "src", "lib.rs"])
    write_if_changed!(manifest, Manifest.encode!(opts[:crate], opts[:crates]))

    unless File.exists?(source) do
      write_if_changed!(source, "// RustQ.Native source is generated before Cargo compilation.\n")
    end

    manifest
  end

  defp native_source(items, module) do
    imports =
      A.use(
        {[:rustler], [:Atom, :Binary, :Decoder, :Encoder, :Env, :NifResult, :ResourceArc, :Term]}
      )

    body =
      [imports | items]
      |> Kernel.++([Nif.init(module)])
      |> Enum.map_join("\n\n", &(&1 |> RustQ.Rust.render() |> String.trim()))

    """
    // Generated by RustQ.Native. Do not edit.
    #![allow(unused_imports)]

    #{body}
    """
  end

  defp write_if_changed!(path, content) do
    if not File.exists?(path) or File.read!(path) != content do
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, content)
    end
  end

  defp format_crate!(cargo, manifest, module) do
    {output, status} =
      System.cmd(cargo, ["fmt", "--manifest-path", manifest], stderr_to_stdout: true)

    if status != 0 do
      raise CompileError,
        description:
          "generated RustQ.Native crate for #{inspect(module)} failed to format:\n#{output}"
    end
  end

  defp build_crate!(cargo, manifest, target, mode, module) do
    args =
      ["build", "--manifest-path", manifest] ++
        if mode == :release do
          ["--release"]
        else
          []
        end

    {output, status} =
      System.cmd(cargo, args, env: [{"CARGO_TARGET_DIR", target}], stderr_to_stdout: true)

    if status != 0 do
      raise CompileError,
        description:
          "generated RustQ.Native crate for #{inspect(module)} failed to compile:\n#{output}"
    end
  end

  defp install_library!(target, mode, crate, otp_app) do
    profile =
      if mode == :release do
        "release"
      else
        "debug"
      end

    source = Path.join([target, profile, library_filename(crate)])

    unless File.regular?(source) do
      raise CompileError, description: "Cargo did not produce expected native library #{source}"
    end

    destination_dir = Path.join(Mix.Project.app_path(), "priv/native")

    # Cargo produces .dylib on macOS; the BEAM loader expects .so on Unix.
    installed_filename =
      case :os.type() do
        {:win32, _} -> "#{crate}.dll"
        _unix -> "lib#{crate}.so"
      end

    destination = Path.join(destination_dir, installed_filename)
    File.mkdir_p!(destination_dir)
    File.cp!(source, destination)
    _ = otp_app
    destination
  end

  defp library_filename(crate) do
    case :os.type() do
      {:win32, _} -> "#{crate}.dll"
      {:unix, :darwin} -> "lib#{crate}.dylib"
      _other -> "lib#{crate}.so"
    end
  end
end
